development:
  adapter: postgresql
  encoding: unicode
  database: shopify_app
  pool: 5
  username: user
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: shopify_app
  pool: 5
  username: user
  password:
